name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake GIFs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake-dark.svg?palette=github-dark
      
      - name: Upload snake artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/

  generate-stats:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_border=false&count_private=true&show_icons=true&theme=github_dark
          path: dist/stats.svg
          token: ${{ secrets.PAT }}
      
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&hide_border=false&include_all_commits=true&count_private=true&layout=compact&hide_title=false&langs_count=6&exclude_repo=machineLearningAssignment&theme=github_dark
          path: dist/top-langs.svg
          token: ${{ secrets.PAT }}

      - name: Upload stats artifact
        uses: actions/upload-artifact@v4
        with:
          name: stats
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs:
      - generate-snake
      - generate-stats

    steps:
      - name: Download snake
        uses: actions/download-artifact@v4
        with:
          name: snake
          path: dist/

      - name: Download stats
        uses: actions/download-artifact@v4
        with:
          name: stats
          path: dist/

      - name: Deploy to profile branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist
          publish_branch: profile
          commit_message: "docs(readme): update assets"