name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_border=false&count_private=true&show_icons=true&theme=github_dark
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&hide_border=false&include_all_commits=true&count_private=true&exclude_repo=machineLearningAssignment&theme=github_dark&count_private=true
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Profile Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: profile
          commit_message: "docs(readme): update stats cards"